### ISSUE TITLE
Linux Help

### ISSUE THREAD

**Issue by ThaChillera** [geefr/BSIPA-Linux#6]
Hi,
This issue is BISPA related, not installer related, but since there doesn't seem to be any other Beat Saber  + modding + linux specific discussion on the internet I thought I'd ask here!

I'm running into an issue with multiplayer support for custom songs (https://github.com/Zingabopp/MultiplayerExtensions/issues/112) and they mentioned that if I didn't have a Logs folder, clearly no mods at all work.

Well, since I've been playing some custom songs I would like to beg the differ, so my question is: do you have any idea why I don't have a logs folder?

I've searched high and low for an answer, both --verbose and --plugin-logs don't do anything like documentation says it should.

I've got no ideas other than to step-by-steping the code with a debugger, and I'm personally hoping I don't have to resort to setting up that headache.

Any help would be incredibly appreciated <3

**Comment by ominitay** [comment]
Custom songs work without mods. Are you sure that your mods are working?

**Comment by ThaChillera** [comment]
Yep, mods weren't working. Always used those mod managers I never looked at the BISPA docs, so I never saw the small notice informing wine users of a required dll override.

Fixed, and for future reference: https://bsmg.github.io/BeatSaber-IPA-Reloaded/tags/4.1.6/articles/start-user.html#Note

**Comment by geefr** [comment]
Uh, okay..

If you mean the winhttp override it's been needed for a very long time, and I added it to their docs.

Beataroni should apply that fix automatically, and report an error when installing BSIPA if it can't be applied. (I think I put in a very specific error, that says to paste the logs into a github issue for me).

But if issue closed then cool, apparently I was too busy to even see the issue ;)

**Comment by ThaChillera** [comment]
Yeah, Like I said I initially didn't read the docs so totally missed that.

I tried beataroni but it didn't log anything about setting the dll overrides, so I ended up applying it manually. Maybe it successfully applied, maybe it failed and my wine prefix was just fucked due to me trying many different things.

Beataroni is a great tool btw, thank you so much for making it <3
